language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
gemfile:
  - gemfiles/activerecord-40.gemfile
  - gemfiles/activerecord-41.gemfile
  - gemfiles/activerecord-42.gemfile
matrix:
  allow_failures:
    - rvm: 2.2
